In [6]:
import numpy as np

In [8]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
         ])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
l = [0,1,2,3]

In [10]:
[i*10 for i in l]

[0, 10, 20, 30]

In [12]:
b = np.random.randint(100,size=(3,3))

In [13]:
b

array([[37, 39, 46],
       [30, 44, 17],
       [94, 10, 48]])

In [15]:
b.mean()

40.55555555555556

In [16]:
b>b.mean()

array([[False, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [17]:
b[b>b.mean()]

array([46, 44, 94, 48])